### ISSUE TITLE
»Shrink to fit« doesn't work

### ISSUE THREAD

**Issue by tim-krieger** [nickyreinert/wordCloud-for-Wordpress#14]
Steps to reproduce:

1. Activate option shrink to fit in word cloud settings.
2. Type some words in the textarea, for example `tisch tisch stuhl stuhl fenster fenster schrank schrank`
3. Generate the word cloud

The generated cloud should show the words but the canvas element is white. If I hover over it I can see the tooltips.

**Comment by nickyreinert** [comment]
Seems like it's still not properly shrinking words. Will check this out.

**Comment by tim-krieger** [comment]
After a little bit playing I think I know the cause of this issue:

>Type some words in the textarea, for example` tisch tisch stuhl stuhl fenster fenster schrank schrank`

The canvas is still blank but if you add one of the words I mentioned above the plugin generates a word cloud. This word must have an occurance of +1, which is defined in the word cloud settings in min-word occurrences.

With` tisch tisch tisch stuhl stuhl fenster fenster schrank schrank` the plugin works well.

**Comment by nickyreinert** [comment]
This was caused by a bug. I implemented a pretty strange calculation of the alpha value. If the word list contains words with same occurence (like every word occurs two times), the calculated alpha was 0 (respectively "not a number"). That's why words where invisible.
