### ISSUE TITLE
Add option to load ocr libraries from own premises

### ISSUE THREAD

**Issue by nickyreinert** [nickyreinert/wordCloud-for-Wordpress#3]
Currently OCR data comes from https://unpkg.com and https://tessdata.projectnaptha.com, please add a flag (ocr-local-libraries) to allow user to server data from own premises.

**Comment by nickyreinert** [comment]
Added parameter ocr-local-libraries, set to 1. To use local files, put them to the lib-folder 
(wp-content/plugins/wordCloud-for-Wordpress-2/lib

You will need the language data for the language you want to support. If you download data from here, add .gz as file extension:
https://tesseract-ocr.github.io/tessdoc/Data-Files#data-files-for-version-400-november-29-2016

You also need the worker-library and core-library:
https://unpkg.com/tesseract.js@v2.0.0/dist/worker.min.js
https://unpkg.com/tesseract.js-core@v2.0.0/tesseract-core.wasm.js

**Comment by nilshaffke** [comment]
sorry, referencing the issue was not my plan. guess i will not use hashtags anymore.
